return {
--  'romgrk/barbar.nvim',
--  dependencies = {
--    'lewis6991/gitsigns.nvim',
--    'nvim-tree/nvim-web-devicons',
--  },
--
--  init = function() vim.g.barbar_auto_setup = false end,
--  config = function()
--    require('barbar').setup({
--      animation = true,
--      tabpages = true,
--      auto_hide = false,
--
--      vim.keymap.set('n', '<Tab>', '<Cmd>BufferPrevious<CR>',{silent = true}),
--      vim.keymap.set('n', '<S-Tab>', '<Cmd>BufferNext<CR>',{silent = true}),
--      sidebar_filetypes = {
--        ['neo-tree'] = {event = 'BufWipeout'},
--      }
--    })
--  end
}
